# services/pdf_generator.py
from fpdf import FPDF
import json
from typing import Dict, Any

class PDFGenerator:
    @staticmethod
    def generate_checklist_pdf(content: Dict[str, Any]) -> bytes:
        """Generate PDF from checklist content"""
        pdf = FPDF()
        pdf.add_page()
        
        # Title
        pdf.set_font("Arial", "B", 24)
        pdf.cell(0, 20, content.get("title", "Checklist"), 0, 1, "C")
        pdf.ln(10)
        
        # Steps
        pdf.set_font("Arial", "", 12)
        
        steps = content.get("steps", [])
        for step in steps:
            # Step number and title
            pdf.set_font("Arial", "B", 14)
            step_text = f"Step {step.get('step', '')}: {step.get('title', '')}"
            pdf.cell(0, 10, step_text, 0, 1)
            
            # Description
            pdf.set_font("Arial", "", 11)
            description = step.get('description', '')
            pdf.multi_cell(0, 7, description)
            
            # Time estimate if available
            if step.get('time_estimate'):
                pdf.set_font("Arial", "I", 10)
                pdf.cell(0, 7, f"⏱️ Time: {step['time_estimate']}", 0, 1)
            
            pdf.ln(5)
        
        # Footer
        pdf.set_font("Arial", "I", 10)
        pdf.cell(0, 10, "Generated by LeadMagnet AI", 0, 1, "C")
        
        return pdf.output(dest="S").encode("latin-1")
    
    @staticmethod
    def generate_template_pdf(content: Dict[str, Any]) -> bytes:
        """Generate PDF from template content"""
        pdf = FPDF()
        pdf.add_page()
        
        # Title
        pdf.set_font("Arial", "B", 24)
        pdf.cell(0, 20, content.get("title", "Template"), 0, 1, "C")
        pdf.ln(10)
        
        # Instructions
        pdf.set_font("Arial", "I", 12)
        pdf.cell(0, 10, "Fill in the template below:", 0, 1)
        pdf.ln(5)
        
        # Content
        pdf.set_font("Arial", "", 12)
        template_content = content.get("content", "")
        
        # Simple formatting
        lines = template_content.split('\n')
        for line in lines:
            if line.startswith("# "):
                pdf.set_font("Arial", "B", 16)
                pdf.cell(0, 10, line[2:], 0, 1)
            elif line.startswith("## "):
                pdf.set_font("Arial", "B", 14)
                pdf.cell(0, 8, line[3:], 0, 1)
            else:
                pdf.set_font("Arial", "", 12)
                pdf.multi_cell(0, 6, line)
            pdf.ln(3)
        
        return pdf.output(dest="S").encode("latin-1")